-- AlterTable
ALTER TABLE "Cooldowns" ALTER COLUMN "commentCooldownEnds" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "voxCooldownEnds" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "voteCooldownEnds" SET DEFAULT CURRENT_TIMESTAMP;
